config/routes.rb
Tally::Application.routes.draw do
  get 'users/new'

  get "static_pages/home"

  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :boards, only: [:create, :destroy]
  resources :boards do
    resources :marks
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :marks
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :board
end

app/models/user.rb
class User < ActiveRecord::Base
  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
  has_secure_password
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            format: { with: VALID_EMAIL_REGEX }, 
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  has_many :boards, dependent: :destroy

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :signed_in_user

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      flash[:success] = "Board created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def show
    @board = Board.find(params[:id])
  end

  def destroy
  end

  private

    def board_params
      params.require(:board).permit(:title)
    end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  def create
    @board = Board.find(params[:board_id])
    @mark = @board.marks.create(mark_params)
    if @mark.save
      flash[:success] = "Mark created!"
    else
      flash[:failure] = "Mark not created!"
    end
    redirect_to board_path(@board)
  end
 
  private
    def mark_params
      params.require(:mark).permit(:lat, :lon)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @board = current_user.boards.build if signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:index, :edit, :update, :delete]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @boards = @user.boards.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Tally!" 
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # before filters
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mark_helper.rb
module MarkHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

   def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_board.html.erb
<li class="board-item">
  <h2 class="content"><%= link_to board.title, board %></h2>
  <span class="timestamp">
    Posted <%= time_ago_in_words(board.created_at) %> ago.
  </span>
  <% if current_user?(board.user) %>
    <%= link_to "delete", board, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: board.title %>
  <% end %>
  <br />
  <span>Current mark count: <strong><%= board.marks.count %></strong></span>
</li>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Time</th>
      <th>Location</th>
    </tr>
  </thead>
  <tbody>
  <% @board.marks.each do |m| %>
    <tr>
      <td><%= m.id %></td>
      <td><%= m.created_at.to_formatted_s(:short) %></td>
      <td><strong>Lat:</strong> <%= m.lat %><br />
          <strong>Lon:</strong> <%= m.lon %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= form_for([@board, @board.marks.build], :html => {role: 'form'}) do |f| %>
  <h2>New Mark</h2>
  <div class="row">
    <div class="form-group col-sm-4 col-sm-offset-2">
      <%= f.label :lat, class: 'control-label' %><br>
      <%= f.number_field(:lat, step: 'any', class: 'form-control') %>
    </div>
    <div class="form-group col-sm-4">
      <%= f.label :lon, class: 'control-label' %><br>
      <%= f.number_field(:lon, step: 'any', class: 'form-control')  %>
    </div>
  </div>
  <%= f.submit 'Create', class: 'btn btn-default btn-mark' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      by Oliver Bridgman
    </small>
    <nav>
      <ul>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Tally", root_path, id: "logo", class: "navbar-brand" %>
      <nav>
        <ul class="nav pull-right navbar-nav">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    '#' %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tally</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_board_form.html.erb
<%= form_for(@board) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <fieldset>
    <legend>New Board</legend>
    <div class="form-group">
      <%= f.label :title, class: "control-label" %>
      <%= f.text_field :title, placeholder: "Create a new Board...", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    </div>
  </fieldset>  
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.boards.count, "board") %>
</span>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="col-sm-6 col-sm-offset-3">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/board_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="jumbotron">
    <h1>Welcome to Tally</h1>

     <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@user, :html => { :class => "form-horizontal" }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <fieldset>
        <legend>User Information</legend>
        <div class="form-group">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label :email, class: "control-label" %>
          <%= f.text_field :email, class: "form-control" %>

          <%= f.label :password, class: "control-label" %>
          <%= f.password_field :password, class: "form-control" %>

          <%= f.label :password_confirmation, "Confirm Password", class: "control-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@user, :html => { :class => "form-horizontal" }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <fieldset>
        <legend>User Registration</legend>
        <div class="form-group">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label :email, class: "control-label" %>
          <%= f.text_field :email, class: "form-control" %>

          <%= f.label :password, class: "control-label" %>
          <%= f.password_field :password, class: "form-control" %>

          <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div class="col-sm-12">
    <% if @user.boards.any? %>
      <h3>Boards (<%= @user.boards.count %>)</h3>
      <ol class="boards">
        <%= render @boards %>
      </ol>
      <%= will_paginate @boards %>
  <% end %>
</div>